pipeline {
    agent any

    parameters {
        string(name: 'API_HOST', defaultValue: 'localhost:8080', description: 'API host URL')
        string(name: 'ENV_FILE_ID', defaultValue: '', description: 'id .env file in Jenkins credentials')
    }

    environment {
        HOST = "${params.API_HOST}"
    }

    stages {
        stage('Prepare') {
            steps {
                script {
                    if (!params.ENV_FILE_ID?.trim()) {
                        error "ENV_FILE_ID is not set!"
                    }

                    withCredentials([file(credentialsId: "${params.ENV_FILE_ID}", variable: 'ENV_FILE')]) {
                        sh('cp $ENV_FILE $WORKSPACE/.env')
                    }
                }
            }
        }

        stage('Configure Environment') {
            steps {
                script {
                    sh """
                    ${WORKSPACE}/jenkins/scripts/replace-docs.sh \
                        ${WORKSPACE}/cmd/app \
                        ${HOST}
                    """
                }
            }
        }

        stage('Install Go') {
            steps {
                script {
                    def goVersion = sh(script: 'go version', returnStatus: true)

                    if (goVersion != 0) {
                        echo 'Go is not installed. Installing Go...'

                        sh '''
                        curl -sf -o /tmp/go1.24.1.linux-amd64.tar.gz -L https://dl.google.com/go/go1.24.1.linux-amd64.tar.gz
                        sudo mkdir -p /opt && cd /opt && sudo tar xfz /tmp/go1.24.1.linux-amd64.tar.gz
                        echo "export PATH=\$PATH:/opt/go/bin" >> ~/.bashrc
                        . ~/.bashrc
                        '''

                        sh 'go version'
                    } else {
                        echo 'Go is already installed.'
                    }
                }
            }
        }

        stage('Generate Docs') {
            steps {
                script {
                    sh '''
                    GOPATH=$(go env GOPATH)
                    export PATH=$PATH:$GOPATH/bin
                    go install github.com/swaggo/swag/cmd/swag@latest
                    make swag
                    '''
                }
            }
        }
        
        stage('Build with Docker') {
            steps {
                script {
                    dir(WORKSPACE) {
                        sh """
                        docker compose build --no-cache
                        """
                    }
                }
            }
        }
        
        stage('Deploy') {
            steps {
                script {
                    dir(WORKSPACE) {
                        sh """
                        docker compose down || true
                        docker compose up -d
                        """
                    }
                }
            }
        }

        stage('Clean') {
            steps {
                script {
                    dir(WORKSPACE) {
                         sh """
                        docker system prune -a -f
                        """
                    }
                }
            }
        }
    }
    
    post {
        always {
            cleanWs()
        }
    }
}
